auth:
    resource: '../config/routes/auth/routes.xml'
    prefix: '/api/auth'

api_v1:
    resource: '../config/routes/api/v1/'
    type: directory
    prefix: '/api/v1'

api_login_check:
    path: /api/login_check